# SVC案例

In [1]:
#导数据包
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('weather.csv',index_col=[0])
df

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,24.0,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,22.0,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,20.0,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No
5,2008-12-06,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,...,24.0,55.0,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No
6,2008-12-07,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,24.0,49.0,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No
7,2008-12-08,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,...,17.0,48.0,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No
8,2008-12-09,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,28.0,42.0,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,Yes
9,2008-12-10,Albury,13.1,30.1,1.4,NaN,NaN,W,28.0,S,...,11.0,58.0,27.0,1007.0,1005.7,NaN,NaN,20.1,28.2,No
10,2008-12-11,Albury,13.4,30.4,0.0,NaN,NaN,N,30.0,SSE,...,6.0,48.0,22.0,1011.8,1008.7,NaN,NaN,20.4,28.8,Yes
11,2008-12-12,Albury,15.9,21.7,2.2,NaN,NaN,NNE,31.0,NE,...,13.0,89.0,91.0,1010.5,1004.2,8.0,8.0,15.9,17.0,Yes
12,2008-12-13,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,...,28.0,76.0,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes
13,2008-12-14,Albury,12.6,21.0,3.6,NaN,NaN,SW,44.0,W,...,20.0,65.0,43.0,1001.2,1001.8,NaN,7.0,15.8,19.8,No
14,2008-12-16,Albury,9.8,27.7,NaN,NaN,NaN,WNW,50.0,NaN,...,22.0,50.0,28.0,1013.4,1010.3,0.0,NaN,17.3,26.2,No
15,2008-12-17,Albury,14.1,20.9,0.0,NaN,NaN,ENE,22.0,SSW,...,9.0,69.0,82.0,1012.2,1010.4,8.0,1.0,17.2,18.1,Yes
16,2008-12-18,Albury,13.5,22.9,16.8,NaN,NaN,W,63.0,N,...,20.0,80.0,65.0,1005.8,1002.2,8.0,1.0,18.0,21.5,Yes
17,2008-12-19,Albury,11.2,22.5,10.6,NaN,NaN,SSE,43.0,WSW,...,17.0,47.0,32.0,1009.4,1009.7,NaN,2.0,15.5,21.0,No
18,2008-12-20,Albury,9.8,25.6,0.0,NaN,NaN,SSE,26.0,SE,...,6.0,45.0,26.0,1019.2,1017.1,NaN,NaN,15.8,23.2,No
19,2008-12-21,Albury,11.5,29.3,0.0,NaN,NaN,S,24.0,SE,...,9.0,56.0,28.0,1019.3,1014.8,NaN,NaN,19.1,27.3,No
20,2008-12-22,Albury,17.1,33.0,0.0,NaN,NaN,NE,43.0,NE,...,22.0,38.0,28.0,1013.6,1008.1,NaN,1.0,24.5,31.6,No
21,2008-12-23,Albury,20.5,31.8,0.0,NaN,NaN,WNW,41.0,W,...,20.0,54.0,24.0,1007.8,1005.7,NaN,NaN,23.8,30.8,No
22,2008-12-24,Albury,15.3,30.9,0.0,NaN,NaN,N,33.0,ESE,...,13.0,55.0,23.0,1011.0,1008.2,5.0,NaN,20.9,29.0,No
23,2008-12-25,Albury,12.6,32.4,0.0,NaN,NaN,W,43.0,E,...,19.0,49.0,17.0,1012.9,1010.1,NaN,NaN,21.5,31.2,No
24,2008-12-26,Albury,16.2,33.9,0.0,NaN,NaN,WSW,35.0,SE,...,13.0,45.0,19.0,1010.9,1007.6,NaN,1.0,23.2,33.0,No
25,2008-12-27,Albury,16.9,33.0,0.0,NaN,NaN,WSW,57.0,NaN,...,26.0,41.0,28.0,1006.8,1003.6,NaN,1.0,26.6,31.2,No
26,2008-12-28,Albury,20.1,32.7,0.0,NaN,NaN,WNW,48.0,N,...,30.0,56.0,15.0,1005.2,1001.7,NaN,NaN,24.6,32.1,No
27,2008-12-29,Albury,19.7,27.2,0.0,NaN,NaN,WNW,46.0,NW,...,30.0,49.0,22.0,1004.8,1004.2,NaN,NaN,21.6,26.1,Yes
28,2008-12-30,Albury,12.5,24.2,1.2,NaN,NaN,WNW,50.0,WSW,...,22.0,78.0,70.0,1005.6,1003.4,8.0,8.0,12.5,18.2,No
29,2008-12-31,Albury,12.0,24.4,0.8,NaN,NaN,W,39.0,WNW,...,17.0,48.0,28.0,1006.1,1005.1,1.0,NaN,16.9,22.7,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142163,2017-05-26,Uluru,14.3,27.6,0.4,NaN,NaN,WNW,39.0,NaN,...,20.0,68.0,27.0,1020.5,1016.1,4.0,7.0,16.1,27.2,No
142164,2017-05-27,Uluru,9.3,28.0,0.0,NaN,NaN,W,28.0,SSW,...,11.0,36.0,16.0,1019.9,1016.9,NaN,NaN,16.6,27.3,No
142165,2017-05-28,Uluru,8.0,24.6,0.0,NaN,NaN,E,33.0,SE,...,13.0,46.0,25.0,1021.7,1018.8,4.0,NaN,13.8,23.5,No
142166,2017-05-29,Uluru,12.7,22.2,0.0,NaN,NaN,E,37.0,E,...,13.0,59.0,34.0,1024.3,1021.7,8.0,8.0,13.9,21.0,No
142167,2017-05-30,Uluru,9.4,22.7,0.0,NaN,NaN,E,35.0,SE,...,17.0,62.0,32.0,1026.6,1023.6,8.0,4.0,11.8,22.3,No
142168,2017-05-31,Uluru,5.4,20.5,0.0,NaN,NaN,E,46.0,E,...,28.0,56.0,32.0,1029.2,1025.3,NaN,NaN,11.1,20.2,No
142169,2017-06-01,Uluru,5.6,19.4,0.0,NaN,NaN,E,43.0,E,...,24.0,61.0,22.0,1029.6,1027.1,NaN,NaN,9.7,18.3,No
142170,2017-06-02,Uluru,1.5,19.2,0.0,NaN,NaN,E,37.0,ESE,...,22.0,45.0,18.0,1030.7,1026.7,NaN,NaN,6.8,17.6,No
142171,2017-06-03,Uluru,3.8,19.8,0.0,NaN,NaN,ENE,39.0,ESE,...,17.0,42.0,22.0,1028.7,1024.1,NaN,NaN,8.6,18.9,No
142172,2017-06-04,Uluru,4.5,18.8,0.0,NaN,NaN,E,31.0,ESE,...,15.0,42.0,26.0,1026.9,1022.4,NaN,NaN,9.5,18.6,No
142173,2017-06-05,Uluru,4.9,20.7,0.0,NaN,NaN,E,37.0,ESE,...,24.0,38.0,11.0,1027.1,1023.9,NaN,NaN,10.3,19.8,No
142174,2017-06-06,Uluru,1.2,20.8,0.0,NaN,NaN,E,43.0,ESE,...,28.0,29.0,6.0,1029.8,1025.9,NaN,NaN,7.9,19.9,No
142175,2017-06-07,Uluru,0.5,21.7,0.0,NaN,NaN,E,43.0,ESE,...,20.0,27.0,19.0,1029.0,1025.0,NaN,NaN,9.5,20.5,No
142176,2017-06-08,Uluru,4.0,20.0,0.0,NaN,NaN,SE,39.0,ESE,...,26.0,58.0,26.0,1030.2,1026.7,NaN,NaN,9.1,19.0,No
142177,2017-06-09,Uluru,3.4,19.8,0.0,NaN,NaN,E,43.0,ESE,...,24.0,54.0,23.0,1031.8,1027.7,NaN,NaN,8.7,18.9,No
142178,2017-06-10,Uluru,3.2,18.6,0.0,NaN,NaN,E,46.0,ESE,...,20.0,56.0,29.0,1031.0,1027.2,NaN,NaN,8.2,17.4,No
142179,2017-06-11,Uluru,2.4,19.1,0.0,NaN,NaN,E,33.0,SE,...,17.0,59.0,24.0,1030.0,1026.2,NaN,NaN,8.0,18.8,No
142180,2017-06-12,Uluru,5.1,19.7,0.0,NaN,NaN,E,46.0,ESE,...,17.0,56.0,29.0,1028.5,1025.8,NaN,NaN,8.5,19.2,No
142181,2017-06-13,Uluru,2.5,21.2,0.0,NaN,NaN,ENE,35.0,ESE,...,19.0,57.0,32.0,1027.2,1023.0,NaN,NaN,10.3,20.3,No
142182,2017-06-14,Uluru,2.3,21.4,0.0,NaN,NaN,SE,22.0,SE,...,7.0,60.0,28.0,1026.9,1022.8,NaN,NaN,8.9,20.3,No
142183,2017-06-15,Uluru,2.6,22.5,0.0,NaN,NaN,S,19.0,S,...,7.0,59.0,24.0,1025.0,1021.4,NaN,NaN,8.8,22.1,No
142184,2017-06-16,Uluru,5.2,24.3,0.0,NaN,NaN,E,24.0,SE,...,11.0,53.0,24.0,1023.8,1020.0,NaN,NaN,12.3,23.3,No
142185,2017-06-17,Uluru,6.4,23.4,0.0,NaN,NaN,ESE,31.0,S,...,17.0,53.0,25.0,1025.8,1023.0,NaN,NaN,11.2,23.1,No
142186,2017-06-18,Uluru,8.0,20.7,0.0,NaN,NaN,ESE,41.0,SE,...,26.0,56.0,32.0,1028.1,1024.3,NaN,7.0,11.6,20.0,No
142187,2017-06-19,Uluru,7.4,20.6,0.0,NaN,NaN,E,35.0,ESE,...,17.0,63.0,33.0,1027.2,1023.3,NaN,NaN,11.0,20.3,No
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,ESE,...,13.0,59.0,27.0,1024.7,1021.2,NaN,NaN,9.4,20.9,No
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,11.0,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,9.0,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,9.0,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,7.0,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No

In [3]:
df.shape

(142193, 22)

In [4]:
weather=df.sample(n=5000,random_state=0)
weather

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainTomorrow
86232,2012-10-09,Cairns,17.4,29.0,0.0,3.6,11.1,NNE,33.0,SE,...,19.0,63.0,61.0,1013.1,1008.9,1.0,0.0,26.1,27.8,No
57576,2011-05-24,Bendigo,6.8,14.4,0.8,0.8,NaN,S,46.0,SW,...,22.0,80.0,55.0,1010.2,1012.4,5.0,4.0,10.4,12.7,No
124071,2009-08-06,Walpole,10.1,15.4,14.6,NaN,NaN,WSW,31.0,SW,...,9.0,70.0,61.0,1014.4,1016.1,NaN,NaN,12.3,13.0,No
117955,2009-03-06,Perth,14.4,33.4,0.0,8.0,11.6,SW,41.0,ESE,...,17.0,40.0,23.0,1019.2,1016.6,1.0,0.0,23.0,32.3,No
133468,2010-07-02,AliceSprings,6.8,14.3,10.0,0.2,7.3,E,28.0,ENE,...,13.0,92.0,47.0,1027.6,1024.4,7.0,1.0,7.3,13.7,No
136631,2010-06-11,Darwin,19.3,29.9,0.0,9.2,11.0,ESE,43.0,ESE,...,17.0,44.0,37.0,1015.9,1012.1,1.0,1.0,23.2,29.1,No
75844,2009-04-03,Watsonia,17.9,25.8,0.0,10.6,2.1,SW,44.0,NNE,...,19.0,56.0,99.0,1014.4,1014.9,6.0,8.0,24.7,15.3,Yes
21853,2012-06-20,NorfolkIsland,13.8,20.1,0.0,3.4,6.2,W,65.0,WNW,...,15.0,62.0,81.0,1016.5,1014.8,1.0,7.0,18.2,16.0,Yes
19088,2013-03-11,NorahHead,20.2,26.7,0.4,NaN,NaN,ESE,31.0,S,...,11.0,86.0,64.0,1020.4,1019.6,NaN,NaN,22.7,25.8,No
132305,2015-11-15,Launceston,8.5,20.2,0.0,NaN,NaN,NW,33.0,NNE,...,20.0,70.0,47.0,NaN,NaN,1.0,8.0,12.7,19.2,No
5116,2015-03-02,BadgerysCreek,16.3,22.9,8.4,NaN,NaN,SSW,26.0,SSW,...,9.0,68.0,64.0,1018.9,1017.2,NaN,NaN,18.9,22.2,No
88317,2010-03-23,GoldCoast,21.4,29.1,0.0,NaN,NaN,SSE,46.0,S,...,35.0,71.0,65.0,1018.9,1016.7,NaN,NaN,26.6,27.7,No
10199,2012-07-28,CoffsHarbour,5.6,18.8,0.2,2.2,NaN,WSW,41.0,WSW,...,20.0,44.0,31.0,1015.4,1014.5,0.0,1.0,14.3,18.3,No
99978,2009-01-03,Nuriootpa,10.5,28.9,0.0,8.0,12.9,SE,41.0,ENE,...,7.0,35.0,13.0,1018.0,1014.5,4.0,5.0,16.8,26.4,No
67905,2016-09-24,Melbourne,10.0,20.1,0.0,3.4,7.9,N,54.0,N,...,28.0,66.0,43.0,1009.7,1005.7,5.0,7.0,15.3,19.4,Yes
69997,2014-03-23,Mildura,10.0,21.6,0.0,4.8,6.9,SSW,35.0,SSE,...,19.0,60.0,35.0,1019.1,1019.6,7.0,3.0,11.4,19.7,No
113501,2014-01-04,PearceRAAF,12.0,30.6,0.0,NaN,13.2,SW,41.0,SE,...,28.0,39.0,29.0,1018.1,1014.9,NaN,NaN,22.0,28.1,No
18691,2011-12-09,NorahHead,17.0,23.7,0.4,NaN,NaN,ESE,22.0,SSW,...,17.0,86.0,75.0,1015.1,1013.5,NaN,NaN,19.4,21.8,No
127091,2009-08-22,Hobart,5.9,14.1,3.2,1.0,3.0,WNW,54.0,NNE,...,30.0,66.0,38.0,998.7,997.9,5.0,7.0,9.7,14.0,No
123644,2016-11-24,SalmonGums,7.1,28.4,0.0,NaN,NaN,SE,44.0,ENE,...,15.0,43.0,22.0,NaN,NaN,NaN,NaN,20.1,27.2,No
132401,2016-02-19,Launceston,14.3,23.9,0.0,NaN,NaN,NW,44.0,NNW,...,15.0,78.0,28.0,NaN,NaN,NaN,NaN,18.1,22.4,No
56496,2016-12-02,Ballarat,9.7,20.8,0.0,NaN,NaN,SW,37.0,S,...,15.0,70.0,44.0,1010.8,1012.4,3.0,4.0,13.3,19.5,No
115907,2012-05-24,PerthAirport,4.1,21.9,0.0,3.2,9.3,ENE,33.0,ENE,...,11.0,56.0,24.0,1034.0,1030.5,0.0,1.0,12.1,21.0,No
70019,2014-04-14,Mildura,11.6,22.8,0.0,3.8,10.8,SSE,28.0,SSE,...,13.0,76.0,41.0,1021.6,1019.2,1.0,2.0,15.3,22.0,No
59319,2016-05-01,Bendigo,12.5,15.6,14.4,NaN,NaN,W,56.0,WNW,...,30.0,79.0,53.0,1009.8,1012.6,8.0,8.0,12.5,15.1,No
124566,2011-01-13,Walpole,18.1,35.1,0.0,NaN,NaN,NNW,46.0,N,...,28.0,43.0,48.0,996.3,995.1,NaN,NaN,27.6,26.9,No
84571,2016-09-10,Brisbane,16.2,23.3,7.2,3.4,2.9,NE,28.0,NE,...,7.0,79.0,87.0,1020.0,1016.2,6.0,7.0,21.4,19.7,Yes
34111,2012-07-31,SydneyAirport,7.8,13.9,2.8,3.0,6.3,SSW,54.0,WSW,...,33.0,62.0,63.0,1025.8,1023.0,6.0,6.0,10.3,13.5,No
15269,2010-05-20,Newcastle,9.7,20.5,5.8,NaN,NaN,NaN,NaN,NaN,...,4.0,96.0,64.0,NaN,NaN,7.0,6.0,12.5,19.4,No
131844,2014-08-09,Launceston,4.2,14.2,0.0,NaN,NaN,NNW,35.0,NNW,...,17.0,98.0,80.0,NaN,NaN,8.0,8.0,9.2,12.9,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71327,2013-07-19,Nhil,11.0,14.5,9.0,NaN,NaN,W,57.0,NW,...,28.0,83.0,87.0,1004.1,1004.8,NaN,NaN,11.9,11.7,Yes
70705,2016-03-01,Mildura,14.2,36.9,0.0,8.0,10.8,NE,22.0,ENE,...,9.0,34.0,10.0,1017.6,1014.6,0.0,3.0,22.2,35.0,No
60579,2011-05-24,Sale,8.5,13.6,1.0,1.6,0.8,W,39.0,W,...,22.0,87.0,90.0,1008.1,1011.0,7.0,8.0,10.7,10.8,Yes
115391,2010-11-25,PerthAirport,13.7,29.1,0.0,9.0,13.1,ESE,41.0,ESE,...,26.0,41.0,36.0,1016.5,1013.2,0.0,1.0,23.7,28.3,No
56477,2016-11-13,Ballarat,7.8,14.2,2.2,NaN,NaN,SW,59.0,NNW,...,30.0,99.0,100.0,992.5,994.3,7.0,8.0,8.7,12.7,Yes
26432,2017-02-28,Penrith,18.9,26.6,1.0,NaN,NaN,ESE,30.0,S,...,9.0,91.0,97.0,NaN,NaN,NaN,NaN,22.1,21.0,Yes
5318,2015-09-21,BadgerysCreek,9.5,24.7,0.2,NaN,NaN,SSW,24.0,SE,...,7.0,100.0,38.0,NaN,NaN,NaN,NaN,14.3,23.8,No
103055,2009-03-19,Woomera,18.8,34.6,0.0,13.0,11.5,NaN,NaN,W,...,19.0,26.0,12.0,1014.6,1012.3,1.0,5.0,22.2,33.2,No
96941,2017-06-20,Adelaide,4.9,19.1,0.0,NaN,NaN,N,19.0,NE,...,9.0,82.0,37.0,1028.4,1026.5,NaN,NaN,10.4,18.4,No
106231,2009-08-21,Albany,7.0,16.0,1.0,1.8,8.9,NaN,NaN,NNW,...,4.0,68.0,50.0,1010.1,1005.8,2.0,6.0,10.0,15.5,Yes
29577,2008-04-21,Sydney,14.7,19.3,21.8,7.5,4.6,NaN,NaN,SSW,...,19.0,91.0,70.0,1023.2,1021.4,8.0,7.0,16.6,19.0,Yes
43506,2015-02-14,Wollongong,19.1,25.7,8.0,NaN,NaN,NE,41.0,NNE,...,31.0,78.0,75.0,1023.2,1019.7,NaN,5.0,23.8,24.1,Yes
139943,2015-06-14,Katherine,18.9,33.2,0.0,4.0,NaN,ENE,28.0,ENE,...,13.0,74.0,39.0,1015.0,1010.6,5.0,4.0,24.6,32.8,No
21342,2010-12-26,NorfolkIsland,20.2,25.3,0.0,5.4,2.7,NE,39.0,ENE,...,19.0,79.0,84.0,1015.5,1013.4,7.0,7.0,23.6,23.1,No
6967,2011-11-29,Cobar,22.5,37.1,0.0,13.0,NaN,NaN,NaN,NNE,...,20.0,44.0,29.0,1011.8,NaN,7.0,7.0,25.2,33.6,No
93312,2015-12-24,Townsville,26.5,31.9,0.0,13.8,6.6,ENE,39.0,ENE,...,28.0,59.0,52.0,1009.8,1007.0,7.0,7.0,29.3,30.2,No
137465,2012-10-22,Darwin,24.2,33.4,0.6,7.0,7.8,NW,33.0,NE,...,17.0,63.0,49.0,1011.2,1006.7,5.0,2.0,29.9,32.2,No
16885,2015-03-13,Newcastle,19.0,23.8,9.6,NaN,NaN,NaN,NaN,NaN,...,19.0,93.0,58.0,NaN,NaN,8.0,7.0,19.6,22.8,Yes
39627,2011-05-14,Williamtown,10.9,18.1,0.0,NaN,NaN,W,46.0,WSW,...,26.0,41.0,25.0,1015.9,1017.4,NaN,6.0,15.0,16.7,No
45508,2011-01-02,Canberra,17.9,30.9,5.2,9.4,7.6,W,65.0,W,...,22.0,74.0,44.0,1011.7,1009.6,4.0,4.0,23.7,28.9,No
2703,2016-08-17,Albury,6.0,18.0,0.0,NaN,NaN,NE,22.0,NaN,...,15.0,92.0,65.0,1024.8,1022.6,1.0,7.0,10.6,17.3,No
52649,2014-09-04,MountGinini,-3.4,4.7,0.0,NaN,NaN,SSE,43.0,SE,...,11.0,93.0,73.0,NaN,NaN,NaN,NaN,-0.3,2.2,No
101646,2013-10-29,Nuriootpa,8.1,18.1,0.0,5.4,7.8,S,39.0,S,...,19.0,62.0,41.0,1022.9,1021.6,8.0,3.0,11.2,17.4,No
74619,2014-05-14,Portland,7.9,19.5,0.0,3.2,7.1,N,44.0,N,...,17.0,71.0,58.0,1022.2,1019.1,NaN,7.0,13.9,18.3,No
64957,2015-04-30,MelbourneAirport,5.4,19.3,0.0,1.6,10.1,SSE,28.0,N,...,15.0,76.0,41.0,1031.8,1028.5,1.0,1.0,11.3,19.2,No
68406,2009-08-15,Mildura,5.6,27.6,0.0,4.0,9.6,NNE,56.0,NNE,...,33.0,50.0,15.0,1015.4,1010.2,1.0,1.0,12.9,27.0,Yes
119955,2014-11-24,Perth,11.8,27.0,0.0,8.0,13.2,SW,39.0,ESE,...,20.0,46.0,42.0,1022.1,1018.1,0.0,1.0,19.2,23.4,No
49562,2014-02-24,Tuggeranong,10.6,29.4,0.0,NaN,NaN,NE,35.0,NaN,...,7.0,78.0,28.0,1019.5,1015.4,NaN,NaN,14.9,28.9,No
40925,2016-03-09,Williamtown,20.1,33.6,0.0,7.2,11.2,ENE,39.0,NNE,...,20.0,70.0,45.0,1022.1,1017.9,1.0,1.0,25.1,32.2,No
120597,2016-08-27,Perth,11.2,17.0,31.0,2.6,5.5,WNW,50.0,NW,...,24.0,78.0,72.0,1003.1,1003.6,7.0,3.0,14.6,14.6,Yes

In [5]:
weather.index=range(weather.shape[0])#重置索引
weather.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainTomorrow
0,2012-10-09,Cairns,17.4,29.0,0.0,3.6,11.1,NNE,33.0,SE,...,19.0,63.0,61.0,1013.1,1008.9,1.0,0.0,26.1,27.8,No
1,2011-05-24,Bendigo,6.8,14.4,0.8,0.8,NaN,S,46.0,SW,...,22.0,80.0,55.0,1010.2,1012.4,5.0,4.0,10.4,12.7,No
2,2009-08-06,Walpole,10.1,15.4,14.6,NaN,NaN,WSW,31.0,SW,...,9.0,70.0,61.0,1014.4,1016.1,NaN,NaN,12.3,13.0,No
3,2009-03-06,Perth,14.4,33.4,0.0,8.0,11.6,SW,41.0,ESE,...,17.0,40.0,23.0,1019.2,1016.6,1.0,0.0,23.0,32.3,No
4,2010-07-02,AliceSprings,6.8,14.3,10.0,0.2,7.3,E,28.0,ENE,...,13.0,92.0,47.0,1027.6,1024.4,7.0,1.0,7.3,13.7,No

In [6]:
weather.shape[0]

5000

In [7]:
weather.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainTomorrow'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 142193 entries, 0 to 142192
Data columns (total 22 columns):
Date             142193 non-null object
Location         142193 non-null object
MinTemp          141556 non-null float64
MaxTemp          141871 non-null float64
Rainfall         140787 non-null float64
Evaporation      81350 non-null float64
Sunshine         74377 non-null float64
WindGustDir      132863 non-null object
WindGustSpeed    132923 non-null float64
WindDir9am       132180 non-null object
WindDir3pm       138415 non-null object
WindSpeed9am     140845 non-null float64
WindSpeed3pm     139563 non-null float64
Humidity9am      140419 non-null float64
Humidity3pm      138583 non-null float64
Pressure9am      128179 non-null float64
Pressure3pm      128212 non-null float64
Cloud9am         88536 non-null float64
Cloud3pm         85099 non-null float64
Temp9am          141289 non-null float64
Temp3pm          139467 non-null float64
RainTomorrow     142193 non-null object
dtypes: float64(16), object(6)
memory usage: 25.0+ MB

In [9]:
weather.Date.value_counts()

2009-08-23    9
2009-07-02    7
2013-07-06    7
2015-08-20    7
2015-11-06    7
2013-05-03    6
2017-05-29    6
2009-02-22    6
2016-08-27    6
2015-10-10    6
2012-06-17    6
2015-10-26    6
2010-02-28    6
2016-03-09    6
2015-02-09    6
2014-01-04    6
2016-07-14    5
2016-02-21    5
2011-05-23    5
2017-05-25    5
2012-09-15    5
2012-06-02    5
2012-07-08    5
2009-05-04    5
2011-06-12    5
2010-06-27    5
2014-09-05    5
2015-09-24    5
2013-12-23    5
2009-12-25    5
             ..
2012-01-20    1
2013-07-28    1
2011-08-09    1
2011-10-13    1
2010-12-02    1
2013-11-12    1
2014-04-21    1
2017-06-09    1
2011-03-29    1
2013-01-21    1
2010-07-21    1
2012-04-11    1
2012-06-04    1
2009-01-13    1
2011-10-01    1
2014-03-30    1
2017-03-22    1
2012-05-01    1
2014-05-20    1
2012-04-08    1
2009-04-20    1
2012-01-29    1
2011-10-07    1
2016-02-29    1
2015-09-09    1
2012-02-27    1
2009-01-31    1
2014-03-22    1
2012-10-29    1
2016-08-28    1
Name: Date, Length: 2486, dtype: int64

In [10]:
len(weather.Location.unique())

49

In [11]:
weather.Location.value_counts()

Newcastle           133
PerthAirport        125
Sydney              125
Darwin              124
Hobart              122
NorahHead           122
Perth               121
Brisbane            121
Adelaide            117
SalmonGums          117
Launceston          116
Wollongong          112
MountGinini         112
PearceRAAF          112
Albany              111
Cairns              109
Watsonia            108
Canberra            108
Ballarat            107
Cobar               107
Albury              107
BadgerysCreek       106
CoffsHarbour        106
Nuriootpa           106
Richmond            105
MelbourneAirport    105
NorfolkIsland       105
Moree               103
AliceSprings        102
SydneyAirport       101
Walpole             100
GoldCoast           100
Witchcliffe          98
MountGambier         97
Bendigo              97
Townsville           97
Tuggeranong          97
Sale                 95
Penrith              94
Mildura              94
Williamtown          91
Portland             89
Melbourne            86
Woomera              80
WaggaWagga           78
Dartmoor             78
Uluru                55
Katherine            51
Nhil                 48
Name: Location, dtype: int64

In [12]:
weather.Rainfall.value_counts()

0.0     3167
0.2      309
0.4      124
1.0       81
0.6       79
0.8       67
1.4       65
1.2       54
1.8       44
1.6       37
2.2       35
2.6       34
2.4       31
2.0       30
3.0       28
3.6       26
2.8       25
3.2       23
4.0       20
4.2       17
3.8       17
4.8       15
3.4       15
4.6       15
8.0       13
6.0       13
7.8       12
5.6       12
4.4       12
10.0      11
        ...
21.8       1
6.4        1
43.2       1
45.0       1
21.2       1
74.8       1
25.2       1
58.2       1
20.4       1
27.4       1
14.2       1
32.2       1
23.6       1
46.8       1
73.2       1
53.6       1
19.0       1
29.8       1
57.6       1
11.6       1
53.8       1
24.6       1
19.6       1
38.8       1
38.0       1
33.0       1
8.5        1
27.0       1
42.0       1
54.2       1
Name: Rainfall, Length: 198, dtype: int64

In [13]:
weather.Cloud9am.value_counts()

7.0    686
1.0    538
8.0    488
0.0    307
6.0    273
2.0    239
5.0    220
3.0    209
4.0    163
Name: Cloud9am, dtype: int64

In [14]:
#查看整体信息
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
Date             5000 non-null object
Location         5000 non-null object
MinTemp          4968 non-null float64
MaxTemp          4986 non-null float64
Rainfall         4937 non-null float64
Evaporation      2813 non-null float64
Sunshine         2592 non-null float64
WindGustDir      4640 non-null object
WindGustSpeed    4642 non-null float64
WindDir9am       4650 non-null object
WindDir3pm       4854 non-null object
WindSpeed9am     4951 non-null float64
WindSpeed3pm     4896 non-null float64
Humidity9am      4947 non-null float64
Humidity3pm      4869 non-null float64
Pressure9am      4459 non-null float64
Pressure3pm      4458 non-null float64
Cloud9am         3123 non-null float64
Cloud3pm         2989 non-null float64
Temp9am          4974 non-null float64
Temp3pm          4895 non-null float64
RainTomorrow     5000 non-null object
dtypes: float64(16), object(6)
memory usage: 859.5+ KB

In [15]:
#分别提取特征矩阵和标签
X=weather.iloc[:,:-1]
Y=weather.iloc[:,-1]

In [16]:
np.unique(Y)

array(['No', 'Yes'], dtype=object)

In [17]:
#查看缺失值的比例（列）
X.isna().mean().max()

0.4816

In [18]:
#切分训练集和测试集
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split

In [19]:
#分训练集和测试集
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X,Y,test_size=0.3,random_state=420)

In [20]:
#恢复索引
for i in [Xtrain, Xtest, Ytrain, Ytest]:
    i.index = range(i.shape[0])

In [21]:
Xtrain

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
0,2016-03-14,Williamtown,19.0,29.8,0.0,7.6,7.6,SE,28.0,NW,...,13.0,19.0,83.0,58.0,1016.4,1013.5,7.0,3.0,23.3,29.2
1,2014-09-15,Hobart,5.8,12.6,0.0,3.4,6.8,ESE,31.0,N,...,15.0,19.0,NaN,46.0,1019.0,1016.6,7.0,1.0,8.1,11.6
2,2017-06-14,GoldCoast,16.3,20.6,17.8,NaN,NaN,SE,72.0,S,...,37.0,52.0,100.0,100.0,1023.3,1022.7,NaN,NaN,18.1,20.0
3,2015-07-17,Watsonia,6.6,11.8,2.6,1.2,2.0,S,39.0,SW,...,11.0,20.0,100.0,81.0,1022.0,1021.7,8.0,7.0,8.1,11.5
4,2015-01-12,Uluru,18.0,34.6,0.0,NaN,NaN,SW,39.0,E,...,2.0,17.0,64.0,32.0,1006.7,1003.1,NaN,1.0,24.6,33.2
5,2017-02-25,Launceston,13.3,23.2,0.0,NaN,NaN,NNW,35.0,SSE,...,17.0,9.0,43.0,33.0,NaN,NaN,6.0,1.0,14.5,22.4
6,2014-09-14,Richmond,9.1,25.5,0.0,NaN,NaN,SE,35.0,ENE,...,6.0,4.0,95.0,41.0,1020.8,1014.9,3.0,1.0,14.0,25.2
7,2016-08-02,Cobar,8.5,10.1,1.0,2.0,NaN,SW,44.0,SSW,...,15.0,20.0,96.0,90.0,1013.3,1012.9,8.0,8.0,9.9,8.5
8,2013-01-14,Cairns,21.4,31.1,0.0,10.4,12.3,NNE,31.0,E,...,7.0,17.0,63.0,58.0,1009.5,1007.1,2.0,1.0,28.8,30.4
9,2013-05-11,Ballarat,9.4,21.7,0.0,NaN,NaN,N,50.0,NNE,...,20.0,35.0,66.0,36.0,1027.5,1022.9,NaN,NaN,14.2,20.3
10,2015-10-01,Launceston,6.2,15.3,0.0,NaN,NaN,NNW,48.0,NNW,...,24.0,28.0,71.0,77.0,NaN,NaN,8.0,8.0,11.5,14.0
11,2013-01-14,SalmonGums,18.8,32.8,1.4,NaN,NaN,NE,39.0,NE,...,19.0,11.0,91.0,51.0,NaN,NaN,NaN,NaN,18.9,30.3
12,2013-09-07,Sale,8.1,17.6,0.0,1.2,5.0,WSW,56.0,W,...,15.0,28.0,65.0,50.0,1023.9,1022.8,4.0,6.0,13.9,16.2
13,2008-12-27,Perth,14.9,28.8,0.0,9.4,13.2,SW,39.0,S,...,9.0,19.0,56.0,36.0,1013.2,1011.3,0.0,0.0,20.2,28.4
14,2015-06-30,Richmond,5.7,16.8,0.0,NaN,NaN,S,15.0,WSW,...,7.0,4.0,98.0,75.0,1029.8,1024.9,8.0,NaN,7.2,15.7
15,2013-07-10,Nuriootpa,0.8,13.1,0.2,1.0,8.9,NNE,20.0,NE,...,9.0,11.0,72.0,52.0,1030.2,1028.0,0.0,4.0,6.8,12.6
16,2014-01-22,Townsville,25.8,33.0,0.0,10.8,12.3,ENE,39.0,E,...,19.0,33.0,58.0,53.0,1010.7,1008.4,4.0,2.0,30.0,32.2
17,2016-03-01,Mildura,14.2,36.9,0.0,8.0,10.8,NE,22.0,ENE,...,9.0,9.0,34.0,10.0,1017.6,1014.6,0.0,3.0,22.2,35.0
18,2010-03-20,Walpole,11.3,23.5,1.2,NaN,NaN,SE,33.0,SSE,...,7.0,22.0,97.0,65.0,1019.0,1018.4,NaN,NaN,18.1,22.6
19,2015-08-04,Canberra,-5.3,8.9,0.0,NaN,NaN,NW,48.0,NaN,...,0.0,31.0,86.0,50.0,1023.1,1018.7,NaN,NaN,0.1,7.4
20,2015-11-12,Townsville,24.2,31.4,0.0,11.2,11.2,ENE,39.0,E,...,17.0,28.0,58.0,55.0,1016.6,1013.6,7.0,4.0,28.6,29.1
21,2010-02-27,MountGambier,16.2,23.3,0.0,8.0,2.7,SSE,57.0,SSE,...,28.0,41.0,69.0,63.0,1020.8,1020.9,7.0,7.0,17.6,19.3
22,2013-07-19,Nhil,11.0,14.5,9.0,NaN,NaN,W,57.0,NW,...,30.0,28.0,83.0,87.0,1004.1,1004.8,NaN,NaN,11.9,11.7
23,2016-08-24,Williamtown,11.3,14.8,2.3,NaN,NaN,WSW,39.0,NW,...,13.0,7.0,96.0,81.0,1012.8,1006.7,8.0,8.0,11.8,14.7
24,2011-10-17,Adelaide,8.1,24.1,0.0,10.8,12.3,ENE,28.0,ENE,...,17.0,13.0,49.0,28.0,1032.3,1028.2,NaN,NaN,14.9,22.5
25,2009-01-29,Walpole,15.6,22.7,0.0,NaN,NaN,ESE,28.0,SSE,...,11.0,15.0,58.0,49.0,1010.2,1010.7,NaN,NaN,20.0,21.9
26,2013-07-30,Melbourne,10.3,16.2,2.2,2.2,7.6,W,35.0,W,...,17.0,13.0,80.0,44.0,1022.0,1022.1,3.0,4.0,11.1,15.6
27,2009-03-08,Albury,11.0,30.2,0.0,NaN,NaN,SSE,24.0,E,...,7.0,11.0,54.0,20.0,1017.0,1014.7,NaN,NaN,17.6,28.8
28,2016-10-21,Cairns,23.1,30.3,0.0,9.8,NaN,SE,43.0,SE,...,26.0,31.0,64.0,54.0,1017.2,1014.2,3.0,NaN,28.0,29.0
29,2010-08-04,MountGambier,7.6,11.9,15.0,0.8,3.5,SSW,50.0,S,...,15.0,30.0,97.0,70.0,1017.0,1016.8,8.0,5.0,7.7,8.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3470,2009-06-29,Hobart,6.1,14.7,1.8,1.4,7.3,NNW,43.0,NW,...,24.0,28.0,78.0,54.0,998.9,999.9,1.0,1.0,9.5,13.1
3471,2012-11-06,Sydney,19.6,25.4,0.0,9.0,8.9,NE,57.0,E,...,15.0,30.0,65.0,61.0,1015.8,1012.7,6.0,4.0,24.0,23.9
3472,2011-08-25,NorahHead,10.1,18.5,0.0,NaN,NaN,NE,37.0,N,...,13.0,30.0,77.0,77.0,1026.0,1021.1,NaN,NaN,15.1,17.7
3473,2010-05-24,Albany,11.5,16.1,4.6,2.4,5.2,NaN,NaN,SSW,...,19.0,19.0,65.0,67.0,1016.5,1016.9,7.0,6.0,14.9,15.6
3474,2009-11-24,Penrith,NaN,23.0,NaN,NaN,NaN,SSW,24.0,SW,...,11.0,11.0,81.0,71.0,NaN,NaN,NaN,NaN,17.9,20.9
3475,2015-04-02,Brisbane,19.3,26.7,8.8,2.4,3.0,ENE,30.0,S,...,6.0,4.0,75.0,83.0,1019.5,1015.8,5.0,7.0,24.7,24.2
3476,2015-08-29,Tuggeranong,3.0,14.0,0.2,NaN,NaN,W,33.0,NW,...,11.0,20.0,71.0,43.0,1022.4,1018.6,NaN,NaN,8.8,13.2
3477,2015-02-14,MountGinini,8.1,14.1,0.0,NaN,NaN,NW,41.0,NNW,...,9.0,13.0,70.0,98.0,NaN,NaN,NaN,NaN,12.6,12.0
3478,2016-06-22,Melbourne,11.2,15.4,0.0,2.0,4.5,NW,39.0,NNW,...,13.0,11.0,67.0,68.0,1003.6,1004.6,3.0,7.0,11.9,13.2
3479,2015-04-20,Dartmoor,1.4,16.0,0.2,2.0,8.3,SE,39.0,NaN,...,0.0,19.0,NaN,NaN,1038.8,1036.6,NaN,NaN,7.5,14.5
3480,2015-08-20,Walpole,10.5,16.5,21.4,NaN,NaN,SW,48.0,SW,...,22.0,22.0,97.0,89.0,1008.4,1009.7,NaN,NaN,11.9,13.4
3481,2011-10-09,PearceRAAF,9.6,25.6,NaN,NaN,11.1,E,67.0,E,...,26.0,24.0,58.0,34.0,1016.0,1013.7,NaN,NaN,18.9,25.2
3482,2013-08-26,Melbourne,10.9,19.1,0.4,2.8,6.9,NNW,39.0,N,...,19.0,22.0,67.0,52.0,1023.9,1021.9,4.0,NaN,13.3,17.7
3483,2015-12-01,MountGambier,6.8,16.7,2.4,6.0,8.0,WSW,70.0,WNW,...,22.0,41.0,92.0,36.0,1008.4,1012.0,7.0,5.0,11.6,15.4
3484,2009-09-14,MountGambier,3.3,14.2,2.4,2.4,6.5,W,33.0,N,...,15.0,17.0,71.0,47.0,1023.5,1021.2,1.0,6.0,10.8,13.4
3485,2015-05-13,Launceston,0.5,13.3,0.0,NaN,NaN,NW,39.0,NE,...,2.0,17.0,77.0,53.0,NaN,NaN,1.0,7.0,7.0,12.7
3486,2016-06-28,Mildura,0.9,16.1,0.2,1.2,8.1,W,28.0,N,...,6.0,13.0,99.0,48.0,1027.8,1027.2,0.0,NaN,4.0,15.7
3487,2009-03-02,Williamtown,17.1,26.9,0.2,5.6,5.1,SE,39.0,NE,...,2.0,28.0,87.0,61.0,1015.6,1014.4,8.0,3.0,21.5,25.3
3488,2009-08-11,Tuggeranong,2.8,12.9,1.6,NaN,NaN,WNW,33.0,ESE,...,15.0,11.0,89.0,86.0,1014.3,1010.2,NaN,NaN,7.1,11.2
3489,2011-10-22,Townsville,22.5,29.1,0.0,12.0,10.0,ENE,48.0,ESE,...,30.0,31.0,61.0,55.0,1018.4,1015.1,7.0,6.0,25.8,28.1
3490,2017-05-04,Walpole,16.4,21.9,0.0,NaN,NaN,NW,44.0,NW,...,19.0,17.0,85.0,80.0,1015.2,1013.3,NaN,NaN,18.3,19.9
3491,2017-01-16,Tuggeranong,15.2,35.5,0.0,NaN,NaN,NNW,31.0,NNW,...,7.0,17.0,70.0,14.0,1015.4,1010.9,NaN,NaN,20.2,33.2
3492,2015-10-13,Cobar,12.4,28.1,0.0,9.0,NaN,S,31.0,S,...,17.0,11.0,47.0,20.0,1019.5,1017.3,1.0,1.0,17.7,26.6
3493,2013-09-27,Cairns,16.3,29.2,0.0,6.4,10.3,NNE,30.0,E,...,7.0,17.0,61.0,57.0,1016.4,1012.9,1.0,1.0,26.2,27.6
3494,2011-08-08,AliceSprings,5.0,26.9,0.0,4.8,10.5,WSW,33.0,E,...,6.0,9.0,47.0,16.0,1020.8,1015.9,0.0,2.0,12.9,26.2
3495,2015-07-06,Uluru,2.5,23.2,0.0,NaN,NaN,SE,24.0,SSE,...,9.0,9.0,50.0,23.0,1022.0,1019.0,NaN,NaN,11.0,22.4
3496,2015-04-19,Richmond,16.0,23.9,5.6,NaN,NaN,SSE,44.0,SSW,...,19.0,28.0,62.0,61.0,1018.8,1018.8,NaN,NaN,19.4,22.2
3497,2012-02-17,NorahHead,17.9,26.6,0.0,NaN,NaN,NNE,37.0,N,...,6.0,28.0,75.0,73.0,1018.1,1015.5,NaN,NaN,21.4,24.5
3498,2013-05-18,Richmond,1.8,19.8,0.0,NaN,NaN,W,31.0,NaN,...,0.0,17.0,75.0,30.0,1015.4,1012.1,NaN,NaN,10.6,19.5
3499,2012-03-09,Cobar,12.7,27.7,0.0,NaN,NaN,SW,43.0,WSW,...,13.0,17.0,60.0,27.0,1014.0,1012.8,NaN,NaN,18.6,26.6

In [22]:
#查看标签是否存在样本不均衡问题
Ytrain.value_counts()

No     2710
Yes     790
Name: RainTomorrow, dtype: int64

In [23]:
Ytest.value_counts()

No     1137
Yes     363
Name: RainTomorrow, dtype: int64

In [24]:
#对标签进行编码
from sklearn.preprocessing import LabelEncoder #标签专用编码包
from sklearn.preprocessing import OrdinalEncoder#特征专用包

In [25]:
encorder=LabelEncoder().fit(Ytrain)#模型中相当于【0,1】

In [26]:
Ytrain = pd.DataFrame(encorder.transform(Ytrain))
Ytest = pd.DataFrame(encorder.transform(Ytest))

# 处理特征矩阵

In [27]:
#描述性统计
Xtrain.describe([0.01,0.05,0.1,0.25,0.5,0.75,0.9,0.99]).T

,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,99%,max
MinTemp,3477.0,12.340236,6.384294,-6.9,-2.024,2.1,4.3,7.700,12.1,17.0,20.9,25.824,29.1
MaxTemp,3492.0,23.232904,6.992256,-4.1,8.900,12.7,14.6,18.200,22.7,28.1,32.8,39.600,43.7
Rainfall,3460.0,2.106618,6.570495,0.0,0.000,0.0,0.0,0.000,0.0,0.8,6.0,35.400,102.0
Evaporation,1986.0,5.398489,3.837948,0.0,0.400,1.0,1.4,2.725,4.8,7.4,9.8,17.430,52.4
Sunshine,1835.0,7.723869,3.691531,0.0,0.000,0.4,2.0,5.100,8.5,10.6,12.0,13.400,14.3
WindGustSpeed,3254.0,39.878611,13.492322,9.0,15.000,20.0,24.0,31.000,39.0,46.0,57.0,81.000,115.0
WindSpeed9am,3470.0,13.924784,8.861956,0.0,0.000,0.0,4.0,7.000,13.0,19.0,26.0,39.000,52.0
WindSpeed3pm,3426.0,18.765032,8.915825,0.0,2.000,6.0,7.0,13.000,19.0,24.0,30.0,43.000,78.0
Humidity9am,3460.0,68.844509,18.918369,5.0,18.000,35.0,44.0,57.000,70.0,83.0,94.0,100.000,100.0
Humidity3pm,3405.0,51.628781,20.705426,1.0,9.000,17.0,24.0,37.000,52.0,65.0,79.6,97.960,100.0
Pressure9am,3136.0,1017.538520,7.112893,982.0,999.505,1006.1,1008.7,1012.700,1017.6,1022.3,1026.7,1033.300,1038.8
Pressure3pm,3135.0,1015.140542,7.019753,986.4,997.900,1003.9,1006.4,1010.400,1015.1,1019.9,1024.2,1030.566,1036.6
Cloud9am,2213.0,4.463624,2.860557,0.0,0.000,0.0,1.0,1.000,5.0,7.0,8.0,8.000,8.0
Cloud3pm,2118.0,4.540132,2.707265,0.0,0.000,0.0,1.0,2.000,5.0,7.0,8.0,8.000,8.0
Temp9am,3481.0,17.058115,6.410628,-4.2,2.600,7.2,9.0,12.400,16.8,21.5,25.8,31.020,34.3
Temp3pm,3426.0,21.671979,6.852293,-4.4,7.525,11.5,13.2,16.900,21.0,26.4,31.0,38.100,42.4

In [28]:
#描述性统计
Xtest.describe([0.01,0.05,0.1,0.25,0.5,0.75,0.9,0.99]).T

,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,99%,max
MinTemp,1491.0,12.211335,6.458887,-6.3,-2.500,1.50,3.90,7.6,12.2,16.800,20.70,25.610,28.5
MaxTemp,1494.0,23.330857,7.380122,-0.6,7.686,12.60,14.40,18.0,22.7,28.775,33.50,40.500,44.4
Rainfall,1477.0,2.338456,8.114066,0.0,0.000,0.00,0.00,0.0,0.0,0.800,6.20,31.632,164.2
Evaporation,827.0,5.492745,4.007532,0.0,0.200,0.80,1.40,2.6,4.8,7.600,10.40,16.000,58.5
Sunshine,757.0,7.756803,3.815881,0.0,0.000,0.48,1.66,4.9,8.6,10.700,12.30,13.400,14.0
WindGustSpeed,1388.0,40.164986,14.144410,11.0,15.000,20.00,24.00,30.0,39.0,48.000,57.00,87.000,102.0
WindSpeed9am,1481.0,14.135719,9.018514,0.0,0.000,0.00,4.00,7.0,13.0,19.000,26.00,37.400,72.0
WindSpeed3pm,1470.0,18.759184,9.002335,0.0,2.000,6.00,8.80,13.0,19.0,24.000,30.00,44.620,65.0
Humidity9am,1487.0,67.854069,19.342026,8.0,16.860,32.30,42.60,56.0,68.0,83.000,94.00,100.000,100.0
Humidity3pm,1464.0,50.962432,21.100400,4.0,8.000,15.00,23.00,35.0,52.0,65.000,79.00,97.370,100.0
Pressure9am,1323.0,1017.612774,7.341883,984.6,999.344,1006.10,1008.82,1013.2,1017.3,1022.200,1027.50,1034.678,1039.2
Pressure3pm,1323.0,1015.180726,7.250920,986.6,997.210,1003.62,1006.30,1010.6,1015.0,1019.700,1024.88,1032.156,1036.9
Cloud9am,910.0,4.242857,2.888338,0.0,0.000,0.00,0.00,1.0,5.0,7.000,8.00,8.000,8.0
Cloud3pm,871.0,4.311137,2.790930,0.0,0.000,0.00,1.00,1.0,5.0,7.000,8.00,8.000,8.0
Temp9am,1493.0,17.139049,6.734101,-3.4,0.700,6.70,8.70,12.4,17.0,22.000,26.10,31.908,34.8
Temp3pm,1469.0,21.737849,7.202093,-2.1,6.304,11.14,13.08,16.6,21.2,26.700,31.80,38.700,43.4

In [29]:
col=Xtrain.mean().index
col

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm'],
      dtype='object')

In [30]:
len(col)

16

In [31]:
Xtrain.mean()#返回每一列的均值

MinTemp            12.340236
MaxTemp            23.232904
Rainfall            2.106618
Evaporation         5.398489
Sunshine            7.723869
WindGustSpeed      39.878611
WindSpeed9am       13.924784
WindSpeed3pm       18.765032
Humidity9am        68.844509
Humidity3pm        51.628781
Pressure9am      1017.538520
Pressure3pm      1015.140542
Cloud9am            4.463624
Cloud3pm            4.540132
Temp9am            17.058115
Temp3pm            21.671979
dtype: float64

In [32]:
#查看训练集各列异常值的比例
(np.abs((Xtrain.loc[:,col] - Xtrain.mean())/Xtrain.std())>3).sum()/Xtrain.shape[0]

MinTemp          0.000286
MaxTemp          0.002286
Rainfall         0.021714
Evaporation      0.006286
Sunshine         0.000000
WindGustSpeed    0.010571
WindSpeed9am     0.009714
WindSpeed3pm     0.006000
Humidity9am      0.003714
Humidity3pm      0.000000
Pressure9am      0.003429
Pressure3pm      0.002857
Cloud9am         0.000000
Cloud3pm         0.000000
Temp9am          0.001143
Temp3pm          0.002571
dtype: float64

In [33]:
Xtrain.loc[:,col]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
0,19.0,29.8,0.0,7.6,7.6,28.0,13.0,19.0,83.0,58.0,1016.4,1013.5,7.0,3.0,23.3,29.2
1,5.8,12.6,0.0,3.4,6.8,31.0,15.0,19.0,NaN,46.0,1019.0,1016.6,7.0,1.0,8.1,11.6
2,16.3,20.6,17.8,NaN,NaN,72.0,37.0,52.0,100.0,100.0,1023.3,1022.7,NaN,NaN,18.1,20.0
3,6.6,11.8,2.6,1.2,2.0,39.0,11.0,20.0,100.0,81.0,1022.0,1021.7,8.0,7.0,8.1,11.5
4,18.0,34.6,0.0,NaN,NaN,39.0,2.0,17.0,64.0,32.0,1006.7,1003.1,NaN,1.0,24.6,33.2
5,13.3,23.2,0.0,NaN,NaN,35.0,17.0,9.0,43.0,33.0,NaN,NaN,6.0,1.0,14.5,22.4
6,9.1,25.5,0.0,NaN,NaN,35.0,6.0,4.0,95.0,41.0,1020.8,1014.9,3.0,1.0,14.0,25.2
7,8.5,10.1,1.0,2.0,NaN,44.0,15.0,20.0,96.0,90.0,1013.3,1012.9,8.0,8.0,9.9,8.5
8,21.4,31.1,0.0,10.4,12.3,31.0,7.0,17.0,63.0,58.0,1009.5,1007.1,2.0,1.0,28.8,30.4
9,9.4,21.7,0.0,NaN,NaN,50.0,20.0,35.0,66.0,36.0,1027.5,1022.9,NaN,NaN,14.2,20.3
10,6.2,15.3,0.0,NaN,NaN,48.0,24.0,28.0,71.0,77.0,NaN,NaN,8.0,8.0,11.5,14.0
11,18.8,32.8,1.4,NaN,NaN,39.0,19.0,11.0,91.0,51.0,NaN,NaN,NaN,NaN,18.9,30.3
12,8.1,17.6,0.0,1.2,5.0,56.0,15.0,28.0,65.0,50.0,1023.9,1022.8,4.0,6.0,13.9,16.2
13,14.9,28.8,0.0,9.4,13.2,39.0,9.0,19.0,56.0,36.0,1013.2,1011.3,0.0,0.0,20.2,28.4
14,5.7,16.8,0.0,NaN,NaN,15.0,7.0,4.0,98.0,75.0,1029.8,1024.9,8.0,NaN,7.2,15.7
15,0.8,13.1,0.2,1.0,8.9,20.0,9.0,11.0,72.0,52.0,1030.2,1028.0,0.0,4.0,6.8,12.6
16,25.8,33.0,0.0,10.8,12.3,39.0,19.0,33.0,58.0,53.0,1010.7,1008.4,4.0,2.0,30.0,32.2
17,14.2,36.9,0.0,8.0,10.8,22.0,9.0,9.0,34.0,10.0,1017.6,1014.6,0.0,3.0,22.2,35.0
18,11.3,23.5,1.2,NaN,NaN,33.0,7.0,22.0,97.0,65.0,1019.0,1018.4,NaN,NaN,18.1,22.6
19,-5.3,8.9,0.0,NaN,NaN,48.0,0.0,31.0,86.0,50.0,1023.1,1018.7,NaN,NaN,0.1,7.4
20,24.2,31.4,0.0,11.2,11.2,39.0,17.0,28.0,58.0,55.0,1016.6,1013.6,7.0,4.0,28.6,29.1
21,16.2,23.3,0.0,8.0,2.7,57.0,28.0,41.0,69.0,63.0,1020.8,1020.9,7.0,7.0,17.6,19.3
22,11.0,14.5,9.0,NaN,NaN,57.0,30.0,28.0,83.0,87.0,1004.1,1004.8,NaN,NaN,11.9,11.7
23,11.3,14.8,2.3,NaN,NaN,39.0,13.0,7.0,96.0,81.0,1012.8,1006.7,8.0,8.0,11.8,14.7
24,8.1,24.1,0.0,10.8,12.3,28.0,17.0,13.0,49.0,28.0,1032.3,1028.2,NaN,NaN,14.9,22.5
25,15.6,22.7,0.0,NaN,NaN,28.0,11.0,15.0,58.0,49.0,1010.2,1010.7,NaN,NaN,20.0,21.9
26,10.3,16.2,2.2,2.2,7.6,35.0,17.0,13.0,80.0,44.0,1022.0,1022.1,3.0,4.0,11.1,15.6
27,11.0,30.2,0.0,NaN,NaN,24.0,7.0,11.0,54.0,20.0,1017.0,1014.7,NaN,NaN,17.6,28.8
28,23.1,30.3,0.0,9.8,NaN,43.0,26.0,31.0,64.0,54.0,1017.2,1014.2,3.0,NaN,28.0,29.0
29,7.6,11.9,15.0,0.8,3.5,50.0,15.0,30.0,97.0,70.0,1017.0,1016.8,8.0,5.0,7.7,8.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3470,6.1,14.7,1.8,1.4,7.3,43.0,24.0,28.0,78.0,54.0,998.9,999.9,1.0,1.0,9.5,13.1
3471,19.6,25.4,0.0,9.0,8.9,57.0,15.0,30.0,65.0,61.0,1015.8,1012.7,6.0,4.0,24.0,23.9
3472,10.1,18.5,0.0,NaN,NaN,37.0,13.0,30.0,77.0,77.0,1026.0,1021.1,NaN,NaN,15.1,17.7
3473,11.5,16.1,4.6,2.4,5.2,NaN,19.0,19.0,65.0,67.0,1016.5,1016.9,7.0,6.0,14.9,15.6
3474,NaN,23.0,NaN,NaN,NaN,24.0,11.0,11.0,81.0,71.0,NaN,NaN,NaN,NaN,17.9,20.9
3475,19.3,26.7,8.8,2.4,3.0,30.0,6.0,4.0,75.0,83.0,1019.5,1015.8,5.0,7.0,24.7,24.2
3476,3.0,14.0,0.2,NaN,NaN,33.0,11.0,20.0,71.0,43.0,1022.4,1018.6,NaN,NaN,8.8,13.2
3477,8.1,14.1,0.0,NaN,NaN,41.0,9.0,13.0,70.0,98.0,NaN,NaN,NaN,NaN,12.6,12.0
3478,11.2,15.4,0.0,2.0,4.5,39.0,13.0,11.0,67.0,68.0,1003.6,1004.6,3.0,7.0,11.9,13.2
3479,1.4,16.0,0.2,2.0,8.3,39.0,0.0,19.0,NaN,NaN,1038.8,1036.6,NaN,NaN,7.5,14.5
3480,10.5,16.5,21.4,NaN,NaN,48.0,22.0,22.0,97.0,89.0,1008.4,1009.7,NaN,NaN,11.9,13.4
3481,9.6,25.6,NaN,NaN,11.1,67.0,26.0,24.0,58.0,34.0,1016.0,1013.7,NaN,NaN,18.9,25.2
3482,10.9,19.1,0.4,2.8,6.9,39.0,19.0,22.0,67.0,52.0,1023.9,1021.9,4.0,NaN,13.3,17.7
3483,6.8,16.7,2.4,6.0,8.0,70.0,22.0,41.0,92.0,36.0,1008.4,1012.0,7.0,5.0,11.6,15.4
3484,3.3,14.2,2.4,2.4,6.5,33.0,15.0,17.0,71.0,47.0,1023.5,1021.2,1.0,6.0,10.8,13.4
3485,0.5,13.3,0.0,NaN,NaN,39.0,2.0,17.0,77.0,53.0,NaN,NaN,1.0,7.0,7.0,12.7
3486,0.9,16.1,0.2,1.2,8.1,28.0,6.0,13.0,99.0,48.0,1027.8,1027.2,0.0,NaN,4.0,15.7
3487,17.1,26.9,0.2,5.6,5.1,39.0,2.0,28.0,87.0,61.0,1015.6,1014.4,8.0,3.0,21.5,25.3
3488,2.8,12.9,1.6,NaN,NaN,33.0,15.0,11.0,89.0,86.0,1014.3,1010.2,NaN,NaN,7.1,11.2
3489,22.5,29.1,0.0,12.0,10.0,48.0,30.0,31.0,61.0,55.0,1018.4,1015.1,7.0,6.0,25.8,28.1
3490,16.4,21.9,0.0,NaN,NaN,44.0,19.0,17.0,85.0,80.0,1015.2,1013.3,NaN,NaN,18.3,19.9
3491,15.2,35.5,0.0,NaN,NaN,31.0,7.0,17.0,70.0,14.0,1015.4,1010.9,NaN,NaN,20.2,33.2
3492,12.4,28.1,0.0,9.0,NaN,31.0,17.0,11.0,47.0,20.0,1019.5,1017.3,1.0,1.0,17.7,26.6
3493,16.3,29.2,0.0,6.4,10.3,30.0,7.0,17.0,61.0,57.0,1016.4,1012.9,1.0,1.0,26.2,27.6
3494,5.0,26.9,0.0,4.8,10.5,33.0,6.0,9.0,47.0,16.0,1020.8,1015.9,0.0,2.0,12.9,26.2
3495,2.5,23.2,0.0,NaN,NaN,24.0,9.0,9.0,50.0,23.0,1022.0,1019.0,NaN,NaN,11.0,22.4
3496,16.0,23.9,5.6,NaN,NaN,44.0,19.0,28.0,62.0,61.0,1018.8,1018.8,NaN,NaN,19.4,22.2
3497,17.9,26.6,0.0,NaN,NaN,37.0,6.0,28.0,75.0,73.0,1018.1,1015.5,NaN,NaN,21.4,24.5
3498,1.8,19.8,0.0,NaN,NaN,31.0,0.0,17.0,75.0,30.0,1015.4,1012.1,NaN,NaN,10.6,19.5
3499,12.7,27.7,0.0,NaN,NaN,43.0,13.0,17.0,60.0,27.0,1014.0,1012.8,NaN,NaN,18.6,26.6

In [34]:
#提取出所有训练集所有异常值的索引
deltrain = []
for i in col:
    bool_ = np.abs((Xtrain.loc[:,i] - Xtrain.loc[:,i].mean())/Xtrain.loc[:,i].std())>3
    ind = Xtrain[bool_].index
    deltrain.extend(list(ind))

In [35]:
#去重之后有异常值的行索引
deltrain1 = list(set(deltrain))

In [36]:
#查看测试集各列异常值（注意这里的均值和方差需要用训练集的）
(np.abs((Xtest.loc[:,col] - Xtrain.mean())/Xtrain.std())>3).sum()/Xtest.shape[0]

MinTemp          0.000000
MaxTemp          0.004000
Rainfall         0.024667
Evaporation      0.004667
Sunshine         0.000000
WindGustSpeed    0.013333
WindSpeed9am     0.007333
WindSpeed3pm     0.010000
Humidity9am      0.004667
Humidity3pm      0.000000
Pressure9am      0.004000
Pressure3pm      0.004000
Cloud9am         0.000000
Cloud3pm         0.000000
Temp9am          0.000667
Temp3pm          0.005333
dtype: float64

In [37]:
#提取出测试集的所有异常值的索引
deltest = []
for i in col:
    bool_ = np.abs((Xtest.loc[:,i] - Xtrain.loc[:,i].mean())/Xtrain.loc[:,i].std())>3
    ind = Xtest[bool_].index
    deltest.extend(list(ind))

In [38]:
#去重之后有异常值的行索引
deltest1 = list(set(deltest))

In [39]:
#删除训练集特征的异常值
Xtrain = Xtrain.drop(index=deltrain1)

In [40]:
Xtrain.shape

(3301, 21)

In [41]:
#删除训练集标签的异常值
Ytrain = Ytrain.drop(index=deltrain1)

In [42]:
Ytrain.shape

(3301, 1)

In [43]:
#删除测试集特征的异常值
Xtest= Xtest.drop(index=deltest1)

In [44]:
Xtest.shape

(1410, 21)

In [45]:
#删除测试集标签的异常值
Ytest= Ytest.drop(index=deltest1)

In [46]:
Ytest.shape

(1410, 1)

In [47]:
#进行任何行删除之后，千万记得要恢复索引
for i in [Xtrain, Xtest, Ytrain, Ytest]:
    i.index = range(i.shape[0])

# 处理困难特征：日期

In [48]:
Xtrain.Date.value_counts()

2015-11-06    6
2009-08-23    6
2009-11-29    5
2016-02-21    5
2009-08-14    5
2009-02-22    5
2015-02-06    5
2015-07-13    5
2013-08-22    5
2015-10-10    5
2011-09-11    5
2015-02-09    5
2015-01-18    5
2014-04-18    4
2016-03-09    4
2013-12-23    4
2016-04-09    4
2014-09-15    4
2010-04-25    4
2017-05-29    4
2017-02-25    4
2010-06-27    4
2015-08-20    4
2012-04-24    4
2014-10-26    4
2012-04-04    4
2016-12-10    4
2014-12-22    4
2011-07-21    4
2009-03-23    4
             ..
2017-03-19    1
2016-05-28    1
2015-11-03    1
2010-02-04    1
2010-06-08    1
2014-04-02    1
2014-12-21    1
2014-05-03    1
2015-08-31    1
2013-07-29    1
2009-11-08    1
2015-08-22    1
2013-11-06    1
2014-06-13    1
2011-06-10    1
2010-01-23    1
2011-11-28    1
2010-02-01    1
2009-05-08    1
2009-04-02    1
2010-01-26    1
2009-12-16    1
2016-03-06    1
2009-02-06    1
2014-08-21    1
2012-09-29    1
2010-09-09    1
2014-01-14    1
2011-05-02    1
2012-05-13    1
Name: Date, Length: 2025, dtype: int64

In [49]:
sum(Xtrain.Date=='2015-11-06')

6

In [50]:
Xtrain[Xtrain.Date=='2015-11-06']

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
138,2015-11-06,MountGambier,12.4,16.5,1.6,1.8,3.7,WSW,39.0,SW,...,17.0,26.0,96.0,64.0,1013.3,1014.2,8.0,7.0,12.6,15.0
1204,2015-11-06,CoffsHarbour,20.1,28.3,7.2,NaN,NaN,NE,46.0,NNE,...,17.0,31.0,81.0,66.0,1010.9,1006.4,NaN,NaN,23.3,25.6
1854,2015-11-06,Ballarat,12.6,15.0,1.4,NaN,NaN,WSW,35.0,SW,...,17.0,22.0,100.0,99.0,1010.2,1010.9,7.0,8.0,12.8,14.8
2332,2015-11-06,MountGinini,7.5,10.8,16.0,NaN,NaN,W,43.0,W,...,15.0,11.0,97.0,97.0,NaN,NaN,NaN,NaN,8.5,9.7
2732,2015-11-06,Newcastle,17.7,30.0,2.0,NaN,NaN,NaN,NaN,N,...,9.0,NaN,75.0,NaN,NaN,NaN,5.0,NaN,24.0,NaN
2911,2015-11-06,Launceston,15.8,26.2,5.0,NaN,NaN,NNW,35.0,NNW,...,4.0,20.0,88.0,66.0,NaN,NaN,7.0,8.0,17.9,24.1

In [51]:
#查看重复值
Xtrain.duplicated().sum()
#删除重复值用drop.duplicates()

0

In [52]:
#查看日期的种类（个数）方法一
Xtrain.Date.value_counts().count()

2025

In [53]:
#查看日期的种类（个数）方法二
len(set(Xtrain.Date))

2025

In [54]:
Xtrain['Rainfall'].head()

0    0.0
1    0.0
2    2.6
3    0.0
4    0.0
Name: Rainfall, dtype: float64

In [55]:
#查看Rainfall列是否有缺失值
Xtrain.Rainfall.isna().sum()

38

In [56]:
Xtrain.loc[Xtrain["Rainfall"] >= 1,"RainToday"] = "Yes"
Xtrain.loc[Xtrain["Rainfall"] < 1,"RainToday"] = "No"
Xtrain.loc[Xtrain["Rainfall"] == np.nan,"RainToday"] = np.nan

Xtest.loc[Xtest["Rainfall"] >= 1,"RainToday"] = "Yes"
Xtest.loc[Xtest["Rainfall"] < 1,"RainToday"] = "No"
Xtest.loc[Xtest["Rainfall"] == np.nan,"RainToday"] = np.nan

Xtrain.head()
Xtest.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,2015-07-16,Launceston,-0.6,10.8,0.0,NaN,NaN,SE,20.0,E,...,7.0,94.0,54.0,NaN,NaN,NaN,NaN,1.9,10.6,No
1,2015-04-28,Adelaide,8.7,16.7,0.0,1.6,NaN,SE,22.0,NaN,...,9.0,68.0,46.0,1030.8,1028.4,NaN,NaN,14.1,16.0,No
2,2015-03-21,Portland,7.7,19.0,0.0,5.4,10.3,E,33.0,SE,...,15.0,62.0,50.0,1027.7,1026.0,8.0,1.0,13.9,18.4,No
3,2009-02-22,Portland,14.8,21.7,0.0,2.2,12.5,ESE,33.0,ESE,...,19.0,61.0,47.0,1018.5,1015.2,6.0,3.0,15.9,21.5,No
4,2017-02-20,Portland,10.8,18.2,2.0,NaN,NaN,SSW,37.0,SW,...,22.0,74.0,55.0,1015.8,1016.7,7.0,8.0,13.1,16.8,Yes

In [57]:
Xtrain['RainToday'].value_counts().sum()

3263

In [58]:
Xtrain.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,2016-03-14,Williamtown,19.0,29.8,0.0,7.6,7.6,SE,28.0,NW,...,19.0,83.0,58.0,1016.4,1013.5,7.0,3.0,23.3,29.2,No
1,2014-09-15,Hobart,5.8,12.6,0.0,3.4,6.8,ESE,31.0,N,...,19.0,NaN,46.0,1019.0,1016.6,7.0,1.0,8.1,11.6,No
2,2015-07-17,Watsonia,6.6,11.8,2.6,1.2,2.0,S,39.0,SW,...,20.0,100.0,81.0,1022.0,1021.7,8.0,7.0,8.1,11.5,Yes
3,2015-01-12,Uluru,18.0,34.6,0.0,NaN,NaN,SW,39.0,E,...,17.0,64.0,32.0,1006.7,1003.1,NaN,1.0,24.6,33.2,No
4,2017-02-25,Launceston,13.3,23.2,0.0,NaN,NaN,NNW,35.0,SSE,...,9.0,43.0,33.0,NaN,NaN,6.0,1.0,14.5,22.4,No

In [59]:
#提取月份
int(Xtrain.loc[0,'Date'].split('-')[1])

3

In [60]:

Xtrain["Date"] = Xtrain["Date"].apply(lambda x:int(x.split("-")[1]))
Xtrain = Xtrain.rename(columns={"Date":"Month"})
Xtrain.head()

,Month,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,3,Williamtown,19.0,29.8,0.0,7.6,7.6,SE,28.0,NW,...,19.0,83.0,58.0,1016.4,1013.5,7.0,3.0,23.3,29.2,No
1,9,Hobart,5.8,12.6,0.0,3.4,6.8,ESE,31.0,N,...,19.0,NaN,46.0,1019.0,1016.6,7.0,1.0,8.1,11.6,No
2,7,Watsonia,6.6,11.8,2.6,1.2,2.0,S,39.0,SW,...,20.0,100.0,81.0,1022.0,1021.7,8.0,7.0,8.1,11.5,Yes
3,1,Uluru,18.0,34.6,0.0,NaN,NaN,SW,39.0,E,...,17.0,64.0,32.0,1006.7,1003.1,NaN,1.0,24.6,33.2,No
4,2,Launceston,13.3,23.2,0.0,NaN,NaN,NNW,35.0,SSE,...,9.0,43.0,33.0,NaN,NaN,6.0,1.0,14.5,22.4,No

In [61]:
Xtest["Date"] = Xtest["Date"].apply(lambda x:int(x.split("-")[1]))
Xtest = Xtest.rename(columns={"Date":"Month"})
Xtest.head()

,Month,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,7,Launceston,-0.6,10.8,0.0,NaN,NaN,SE,20.0,E,...,7.0,94.0,54.0,NaN,NaN,NaN,NaN,1.9,10.6,No
1,4,Adelaide,8.7,16.7,0.0,1.6,NaN,SE,22.0,NaN,...,9.0,68.0,46.0,1030.8,1028.4,NaN,NaN,14.1,16.0,No
2,3,Portland,7.7,19.0,0.0,5.4,10.3,E,33.0,SE,...,15.0,62.0,50.0,1027.7,1026.0,8.0,1.0,13.9,18.4,No
3,2,Portland,14.8,21.7,0.0,2.2,12.5,ESE,33.0,ESE,...,19.0,61.0,47.0,1018.5,1015.2,6.0,3.0,15.9,21.5,No
4,2,Portland,10.8,18.2,2.0,NaN,NaN,SSW,37.0,SW,...,22.0,74.0,55.0,1015.8,1016.7,7.0,8.0,13.1,16.8,Yes

#  处理分类型变量的缺失值

In [62]:
#查看缺失值的缺失情况
Xtrain.isna().mean()

Month            0.000000
Location         0.000000
MinTemp          0.006968
MaxTemp          0.002121
Rainfall         0.011512
Evaporation      0.432899
Sunshine         0.475613
WindGustDir      0.069979
WindGustSpeed    0.069676
WindDir9am       0.073614
WindDir3pm       0.029991
WindSpeed9am     0.008482
WindSpeed3pm     0.021509
Humidity9am      0.010906
Humidity3pm      0.027264
Pressure9am      0.102999
Pressure3pm      0.103302
Cloud9am         0.369888
Cloud3pm         0.396547
Temp9am          0.004847
Temp3pm          0.021206
RainToday        0.011512
dtype: float64

In [63]:
#找出分类型变量
Xtrain.columns[Xtrain.dtypes=='object']

Index(['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday'], dtype='object')

In [64]:
#首先找出，分类型特征都有哪些
cate = Xtrain.columns[Xtrain.dtypes == "object"].tolist()

In [65]:
#除了特征类型为"object"的特征们，还有虽然用数字表示，但是本质为分类型特征的云层遮蔽程度
cloud = ["Cloud9am","Cloud3pm"]
cate = cate + cloud
cate

['Location',
 'WindGustDir',
 'WindDir9am',
 'WindDir3pm',
 'RainToday',
 'Cloud9am',
 'Cloud3pm']

In [66]:
#用众数进行填补
from sklearn.impute import SimpleImputer

In [67]:
si = SimpleImputer(missing_values=np.nan,strategy="most_frequent")
#注意，我们使用训练集数据来训练我们的填补器，本质是在生成训练集中的众数
si.fit(Xtrain.loc[:,cate])

#然后我们用训练集中的众数来同时填补训练集和测试集
Xtrain.loc[:,cate] = si.transform(Xtrain.loc[:,cate])
Xtest.loc[:,cate] = si.transform(Xtest.loc[:,cate])

Xtrain.head()
Xtest.head()

,Month,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,7,Launceston,-0.6,10.8,0.0,NaN,NaN,SE,20.0,E,...,7.0,94.0,54.0,NaN,NaN,7.0,7.0,1.9,10.6,No
1,4,Adelaide,8.7,16.7,0.0,1.6,NaN,SE,22.0,N,...,9.0,68.0,46.0,1030.8,1028.4,7.0,7.0,14.1,16.0,No
2,3,Portland,7.7,19.0,0.0,5.4,10.3,E,33.0,SE,...,15.0,62.0,50.0,1027.7,1026.0,8.0,1.0,13.9,18.4,No
3,2,Portland,14.8,21.7,0.0,2.2,12.5,ESE,33.0,ESE,...,19.0,61.0,47.0,1018.5,1015.2,6.0,3.0,15.9,21.5,No
4,2,Portland,10.8,18.2,2.0,NaN,NaN,SSW,37.0,SW,...,22.0,74.0,55.0,1015.8,1016.7,7.0,8.0,13.1,16.8,Yes

In [68]:
#确认训练集中是否还有缺失值
Xtrain.loc[:,cate].isna().sum()

Location       0
WindGustDir    0
WindDir9am     0
WindDir3pm     0
RainToday      0
Cloud9am       0
Cloud3pm       0
dtype: int64

In [69]:
#确认测试集中是否还有缺失值
Xtest.loc[:,cate].isna().sum()

Location       0
WindGustDir    0
WindDir9am     0
WindDir3pm     0
RainToday      0
Cloud9am       0
Cloud3pm       0
dtype: int64

In [70]:
#将所有的分类型变量编码为数字，一个类别是一个数字
from sklearn.preprocessing import OrdinalEncoder#特征变量专用编码包（输入的数据必须为二维或二维以上）
oe = OrdinalEncoder()

In [71]:
#利用训练集进行fit
oe = oe.fit(Xtrain.loc[:,cate])

In [72]:
#用训练集的编码结果来编码训练和测试特征矩阵
#在这里如果测试特征矩阵报错，就说明测试集中出现了训练集中从未见过的类别
Xtrain.loc[:,cate] = oe.transform(Xtrain.loc[:,cate])
Xtest.loc[:,cate] = oe.transform(Xtest.loc[:,cate])

Xtrain.loc[:,cate].head()
Xtest.loc[:,cate].head()

,Location,WindGustDir,WindDir9am,WindDir3pm,RainToday,Cloud9am,Cloud3pm
0,17.0,9.0,0.0,8.0,0.0,7.0,7.0
1,0.0,9.0,3.0,2.0,0.0,7.0,7.0
2,33.0,0.0,9.0,2.0,0.0,8.0,1.0
3,33.0,2.0,2.0,9.0,0.0,6.0,3.0
4,33.0,11.0,12.0,12.0,1.0,7.0,8.0

In [73]:
#提取连续型数据的列名
col = Xtrain.columns.tolist()
for i in cate:
    col.remove(i)

In [74]:
col

['Month',
 'MinTemp',
 'MaxTemp',
 'Rainfall',
 'Evaporation',
 'Sunshine',
 'WindGustSpeed',
 'WindSpeed9am',
 'WindSpeed3pm',
 'Humidity9am',
 'Humidity3pm',
 'Pressure9am',
 'Pressure3pm',
 'Temp9am',
 'Temp3pm']

In [75]:
Xtrain.isna().sum()

Month               0
Location            0
MinTemp            23
MaxTemp             7
Rainfall           38
Evaporation      1429
Sunshine         1570
WindGustDir         0
WindGustSpeed     230
WindDir9am          0
WindDir3pm          0
WindSpeed9am       28
WindSpeed3pm       71
Humidity9am        36
Humidity3pm        90
Pressure9am       340
Pressure3pm       341
Cloud9am            0
Cloud3pm            0
Temp9am            16
Temp3pm            70
RainToday           0
dtype: int64

In [76]:
#将所有的分类型变量编码为数字，一个类别是一个数字
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()

In [77]:
#利用训练集进行fit
oe = oe.fit(Xtrain.loc[:,cate])

In [78]:
#用训练集的编码结果来编码训练和测试特征矩阵
#在这里如果测试特征矩阵报错，就说明测试集中出现了训练集中从未见过的类别
Xtrain.loc[:,cate] = oe.transform(Xtrain.loc[:,cate])
Xtest.loc[:,cate] = oe.transform(Xtest.loc[:,cate])

Xtrain.loc[:,cate].head()
Xtest.loc[:,cate].head()

,Location,WindGustDir,WindDir9am,WindDir3pm,RainToday,Cloud9am,Cloud3pm
0,17.0,9.0,0.0,8.0,0.0,7.0,7.0
1,0.0,9.0,3.0,2.0,0.0,7.0,7.0
2,33.0,0.0,9.0,2.0,0.0,8.0,1.0
3,33.0,2.0,2.0,9.0,0.0,6.0,3.0
4,33.0,11.0,12.0,12.0,1.0,7.0,8.0

# 处理连续型变量：无量纲化

In [79]:
col.remove("Month")
col

['MinTemp',
 'MaxTemp',
 'Rainfall',
 'Evaporation',
 'Sunshine',
 'WindGustSpeed',
 'WindSpeed9am',
 'WindSpeed3pm',
 'Humidity9am',
 'Humidity3pm',
 'Pressure9am',
 'Pressure3pm',
 'Temp9am',
 'Temp3pm']

In [80]:
#去除量纲方法一：标准化
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss = ss.fit(Xtrain.loc[:,col])
Xtrain.loc[:,col] = ss.transform(Xtrain.loc[:,col])
Xtest.loc[:,col] = ss.transform(Xtest.loc[:,col])

Xtrain.head()
Xtest.head()

,Month,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,7,17.0,-2.036511,-1.837684,-0.388206,NaN,NaN,9.0,-1.554551,0.0,...,-1.355480,1.366910,0.143378,NaN,NaN,7.0,7.0,-2.393300,-1.677157,0.0
1,4,0.0,-0.563179,-0.969300,-0.388206,-1.130177,NaN,9.0,-1.388726,3.0,...,-1.115671,-0.041802,-0.256871,1.895123,1.914874,7.0,7.0,-0.462560,-0.864352,0.0
2,3,33.0,-0.721602,-0.630777,-0.388206,0.071687,0.681782,0.0,-0.476687,9.0,...,-0.396242,-0.366889,-0.056747,1.439773,1.559720,8.0,1.0,-0.494211,-0.503106,0.0
3,2,33.0,0.403200,-0.233381,-0.388206,-0.940409,1.288182,2.0,-0.476687,2.0,...,0.083376,-0.421070,-0.206840,0.088410,-0.038475,6.0,3.0,-0.177696,-0.036495,0.0
4,2,33.0,-0.230491,-0.748524,0.209457,NaN,NaN,11.0,-0.145036,12.0,...,0.443091,0.283286,0.193409,-0.308185,0.183496,7.0,8.0,-0.620817,-0.743937,1.0

In [81]:
#去除量纲方法二：归一化
#from sklearn.preprocessing import MinMaxScaler

#mms = MinMaxScaler()
#mms = mms.fit(Xtrain.loc[:,col])
#Xtrain.loc[:,col] = mms.transform(Xtrain.loc[:,col])
#Xtest.loc[:,col] = mms.transform(Xtest.loc[:,col])

#Xtrain.head()
#Xtest.head()

In [82]:
Xtrain.shape

(3301, 22)

In [83]:
from time import time
import datetime
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_auc_score, recall_score

In [84]:
#查看标签
Ytest.head()

   0
0  0
1  0
2  0
3  0
4  0

In [85]:
#对标签进行转换方法一

Ytrain = Ytrain.iloc[:,0].ravel()
Ytest = Ytest.iloc[:,0].ravel()

In [86]:
#对标签进行转换方法二
#Ytrain=Ytrain.iloc[:,0].values()